version: '3'
services:
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: solfarm-api
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAMESPACE: ${DB_NAMESPACE}
      SERVER_PORT: "${SERVER_PORT}"
    restart: always
